### PR TITLE
Star 188 listbox issue 472

### LINKED ISSUE #472: ListBox - search filter not cleared after close via Trigger
# Bug Report

### Observed
When a search string is entered into the search filter field and then the ListBox is closed by clicking the Trigger element or pressing `tab` to move focus away, then when the ListBox is reopened the search filter is cleared, but the search is still applied to the ListBox options list. When the ListBox is initially closed by clicking away (blur) or pressing `esc`, the search filter will be cleared, but the search is no longer applied and the complete list of options is shown.  

###  Expected
The behaviour should be consistent when clicking the Trigger / tabbing away with clicking away / pressing `esc`. Or else the search filter field should persist until the user clears it manually.  

### ScreenCap
listbox - search bug

### PR DESCRIPTION
**Pull request by nahumzs**
### Purpose 🚀
This fixed #472 where the filter was not resetting properly when a onBlur were happening, also fix an issue where using a tab on the trigger was not closing the popover. 

### Notes ✏️
_details of code change / secondary purposes of this PR_

### Updates 📦
- [ ] MAJOR (breaking) change to _these packages_
- [ ] MINOR (backward compatible) change to _these packages_
- [x] PATCH (bug fix) change to _these packages_

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/STAR-188-Listbox-issue-472

### Screenshots 📸
_optional but highly recommended_

### References 🔗
_relevant Jira ticket / GitHub issues_

### CODE REVIEW

File: packages/L10n/build-translations.js [hunk 1]
```diff
@@ -13,7 +13,9 @@ const removeTranslationFiles = () => {
     }
 
     files.forEach(file => {
-      fs.unlinkSync(`${translationsPath}/${file}`);
+      if (file !== ".gitkeep") {
```
Comment (nahumzs) [inline packages/L10n/build-translations.js:16]: we need to keep .gitkeep on the localization folder in order to version the folder in git and use it to process the locale generator script.

File: packages/ListBox/src/components/Filter/Filter.js [hunk 2]
```diff
@@ -40,10 +40,20 @@ const Filter = React.forwardRef((props, ref) => {
...
+    });
+  }, [applyFilterType, dispatch]);
+
   React.useImperativeHandle(ref, () => ({
     clear: () => {
       setTextSearch(() => "");
     },
+    reset: () => {
+      reset();
+    },
```
Comment (allison-c) [inline packages/ListBox/src/components/Filter/Filter.js:56]: just curious can this be `reset: reset` ?

Comment (nahumzs) [reply packages/ListBox/src/components/Filter/Filter.js:56]: indeed :) can.

Comment (mikrotron) [reply packages/ListBox/src/components/Filter/Filter.js:56]: ... or just `reset,`?

Comment (alexzherdev) [reply packages/ListBox/src/components/Filter/Filter.js:56]: or just  ` `! wait, that doesn't work...
